version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - SPHINX_APIDOC_OPTIONS=members,autosummary sphinx-apidoc -f -d 2 -t docs/templates -o docs/source ./secretflow/

sphinx:
  configuration: docs/conf.py

python:
  install:
  - requirements: docs/requirements.txt
